// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "boxstash/internal/endpoint"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeAboutHandler(m, endpoints, options["About"])
	makeNewAuthTokenHandler(m, endpoints, options["NewAuthToken"])
	makeValidateAuthTokenHandler(m, endpoints, options["ValidateAuthToken"])
	makeDeleteAuthTokenHandler(m, endpoints, options["DeleteAuthToken"])
	makeReadOrganizationHandler(m, endpoints, options["ReadOrganization"])
	makeSearchHandler(m, endpoints, options["Search"])
	makeReadBoxHandler(m, endpoints, options["ReadBox"])
	makeCreateBoxHandler(m, endpoints, options["CreateBox"])
	makeUpdateBoxHandler(m, endpoints, options["UpdateBox"])
	makeDeleteBoxHandler(m, endpoints, options["DeleteBox"])
	makeReadVersionHandler(m, endpoints, options["ReadVersion"])
	makeCreateVersionHandler(m, endpoints, options["CreateVersion"])
	makeUpdateVersionHandler(m, endpoints, options["UpdateVersion"])
	makeDeleteVersionHandler(m, endpoints, options["DeleteVersion"])
	makeReleaseVersionHandler(m, endpoints, options["ReleaseVersion"])
	makeRevokeVersionHandler(m, endpoints, options["RevokeVersion"])
	makeReadProviderHandler(m, endpoints, options["ReadProvider"])
	makeCreateProviderHandler(m, endpoints, options["CreateProvider"])
	makeUpdateProviderHandler(m, endpoints, options["UpdateProvider"])
	makeDeleteProviderHandler(m, endpoints, options["DeleteProvider"])
	return m
}
